# Generated by Django 3.2 on 2021-04-22 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210422_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
